table ARQUITETURA
	lineageTag: 3017f658-9cbf-40eb-87d8-289e726c07e3

	column 'Spreadsheet Field'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2ea7c6d6-9803-4c9e-b65a-78a93473cf49
		summarizeBy: none
		sourceColumn: Spreadsheet Field

		variation Variation
			isDefault
			relationship: 401a4a78-03dc-4a0e-8f07-f4cc5359faeb
			defaultHierarchy: LocalDateTable_9949886b-16b2-4865-83c1-e9bb0ec3e5ca.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Cum Budgeted Total Cost'
		dataType: double
		lineageTag: ab0e9345-1020-4bb2-b5a3-0b16b0f0e308
		summarizeBy: sum
		sourceColumn: Cum Budgeted Total Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition ARQUITETURA = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\franc\OneDrive - Xscient\Arquivos BI\CURVAS POR  DISCIPLINA_TBR070.xlsx"), null, true),
				    ARQUITETURA_Sheet = Fonte{[Item="ARQUITETURA",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(ARQUITETURA_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type text}, {"Column8", type date}, {"Column9", type date}, {"Column10", type date}, {"Column11", type date}, {"Column12", type date}, {"Column13", type date}, {"Column14", type date}, {"Column15", type date}, {"Column16", type date}, {"Column17", type date}, {"Column18", type date}, {"Column19", type date}, {"Column20", type date}, {"Column21", type date}, {"Column22", type date}, {"Column23", type date}, {"Column24", type date}, {"Column25", type date}, {"Column26", type date}, {"Column27", type date}, {"Column28", type date}, {"Column29", type date}, {"Column30", type date}, {"Column31", type date}, {"Column32", type date}, {"Column33", type date}, {"Column34", type any}, {"Column35", type any}, {"Column36", type any}, {"Column37", type any}, {"Column38", type any}, {"Column39", type any}, {"Column40", type any}, {"Column41", type any}, {"Column42", type any}, {"Column43", type any}, {"Column44", type any}, {"Column45", type any}, {"Column46", type any}, {"Column47", type any}, {"Column48", type any}, {"Column49", type any}, {"Column50", type any}, {"Column51", type any}, {"Column52", type any}, {"Column53", type any}, {"Column54", type any}, {"Column55", type any}, {"Column56", type any}, {"Column57", type any}, {"Column58", type any}, {"Column59", type any}, {"Column60", type any}, {"Column61", type any}, {"Column62", type any}, {"Column63", type any}, {"Column64", type any}, {"Column65", type any}, {"Column66", type any}, {"Column67", type any}, {"Column68", type any}, {"Column69", type any}, {"Column70", type any}, {"Column71", type any}, {"Column72", type any}, {"Column73", type any}, {"Column74", type any}, {"Column75", type any}, {"Column76", type any}, {"Column77", type any}, {"Column78", type any}, {"Column79", type any}, {"Column80", type any}, {"Column81", type any}, {"Column82", type any}, {"Column83", type any}, {"Column84", type any}, {"Column85", type any}, {"Column86", type any}, {"Column87", type any}, {"Column88", type any}, {"Column89", type any}, {"Column90", type any}, {"Column91", type any}, {"Column92", type any}, {"Column93", type date}}),
				    #"Tabela Transposta" = Table.Transpose(#"Tipo Alterado"),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tabela Transposta", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Activity ID", type any}, {"  Arquitetura", type any}, {"  Arquitetura_1", type any}, {"  Arquitetura_2", type any}, {"  Arquitetura_3", type any}}),
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Tipo Alterado1", [PromoteAllScalars=true]),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos1",{{"Start", type any}, {"11/03/25 A", type any}, {"11/03/25 A_1", type any}, {"11/03/25 A_2", type any}, {"11/03/25 A_3", type any}}),
				    #"Cabeçalhos Promovidos2" = Table.PromoteHeaders(#"Tipo Alterado2", [PromoteAllScalars=true]),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos2",{{"Finish", type any}, {"19/03/2026", type any}, {"19/03/2026_1", type any}, {"19/03/2026_2", type any}, {"19/03/2026_3", type any}}),
				    #"Cabeçalhos Promovidos3" = Table.PromoteHeaders(#"Tipo Alterado3", [PromoteAllScalars=true]),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos3",{{"Late Finish", type any}, {"07/04/2026", type any}, {"07/04/2026_1", type any}, {"07/04/2026_2", type any}, {"07/04/2026_3", type any}}),
				    #"Cabeçalhos Promovidos4" = Table.PromoteHeaders(#"Tipo Alterado4", [PromoteAllScalars=true]),
				    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos4",{{"BL Project Start", type any}, {"11/03/2025", type any}, {"11/03/2025_1", type any}, {"11/03/2025_2", type any}, {"11/03/2025_3", type any}}),
				    #"Cabeçalhos Promovidos5" = Table.PromoteHeaders(#"Tipo Alterado5", [PromoteAllScalars=true]),
				    #"Tipo Alterado6" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos5",{{"BL Project Finish", type any}, {"20/12/2025", type text}, {"20/12/2025_1", type text}, {"20/12/2025_2", type text}, {"20/12/2025_3", type text}}),
				    #"Cabeçalhos Promovidos6" = Table.PromoteHeaders(#"Tipo Alterado6", [PromoteAllScalars=true]),
				    #"Tipo Alterado7" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos6",{{"Spreadsheet Field", type date}, {"BL1 Total Cost", type text}, {"Cum BL1 Total Cost", type text}, {"Budgeted Total Cost", type text}, {"Cum Budgeted Total Cost", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado7",{"BL1 Total Cost", "Cum BL1 Total Cost", "Budgeted Total Cost"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each ([Cum Budgeted Total Cost] <> null)),
				    #"Valor Substituído" = Table.ReplaceValue(#"Linhas Filtradas",",","",Replacer.ReplaceText,{"Cum Budgeted Total Cost"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído",".",",",Replacer.ReplaceText,{"Cum Budgeted Total Cost"}),
				    #"Tipo Alterado8" = Table.TransformColumnTypes(#"Valor Substituído1",{{"Cum Budgeted Total Cost", type number}})
				in
				    #"Tipo Alterado8"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

