table Tabela1
	lineageTag: 61ff4736-9a30-4329-8b4d-849ebd176bef

	measure Medida = 0.8
		lineageTag: 5150e2e6-e972-4383-a45e-1b262a819cc4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Medida 2' = 0.2
		lineageTag: 0d179e21-4b09-405d-a873-5ea4226872f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantidade Itens sem Carro' = 74433
		formatString: 0
		lineageTag: 56505e39-bdaf-4e59-8b98-9fa58acb1ac0

	column data
		dataType: dateTime
		formatString: General Date
		lineageTag: d3901198-78dd-4964-99bf-fd0862812de8
		summarizeBy: none
		sourceColumn: data

		variation Variation
			isDefault
			relationship: e9776a9f-a015-4ad7-bb29-3d3d59ec6041
			defaultHierarchy: LocalDateTable_aa76a35f-3104-4fc2-8d0e-eeb805390bc8.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column tarefa
		dataType: string
		lineageTag: 8c67809e-e63b-41b2-9662-9afed6ed118f
		summarizeBy: none
		sourceColumn: tarefa

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 3dfb39fc-a470-4823-ade1-1fd8a756b067
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column __PowerAppsId__
		dataType: string
		lineageTag: dde70b13-6bb5-4890-85b4-ded53bc7a5a1
		summarizeBy: none
		sourceColumn: __PowerAppsId__

		annotation SummarizationSetBy = Automatic

	partition Tabela1 = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\franc\OneDrive - Xscient\Arquivos Xscient\Power BI\Pasta1.xlsx"), null, true),
				    Tabela1_Table = Fonte{[Item="Tabela1",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela1_Table,{{"data", type datetime}, {"tarefa", type text}, {"status", type text}, {"__PowerAppsId__", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

