table ca-2004-01
	lineageTag: ecb156d2-65df-4db0-9cad-e4494f356274

	column 'Regiao - Sigla'
		dataType: string
		lineageTag: bc6f8888-2d57-42ff-ac47-aa5ca926e37e
		summarizeBy: none
		sourceColumn: Regiao - Sigla

		annotation SummarizationSetBy = Automatic

	column 'Estado - Sigla'
		dataType: string
		lineageTag: 175d8867-f05e-42c2-a075-3dc4f9bbb165
		summarizeBy: none
		sourceColumn: Estado - Sigla

		annotation SummarizationSetBy = Automatic

	column Municipio
		dataType: string
		lineageTag: fcbb4583-58a7-4903-8cb3-1c37b1604110
		summarizeBy: none
		sourceColumn: Municipio

		annotation SummarizationSetBy = Automatic

	column Revenda
		dataType: string
		lineageTag: e8086a4b-7e3a-4bb3-85b6-5a6b8ff1612a
		summarizeBy: none
		sourceColumn: Revenda

		annotation SummarizationSetBy = Automatic

	column 'CNPJ da Revenda'
		dataType: string
		lineageTag: 047fd87e-3c7a-4047-960e-2745012cb6f4
		summarizeBy: none
		sourceColumn: CNPJ da Revenda

		annotation SummarizationSetBy = Automatic

	column 'Nome da Rua'
		dataType: string
		lineageTag: b8a31c85-4da6-4b3f-92fd-f62bccaa6054
		summarizeBy: none
		sourceColumn: Nome da Rua

		annotation SummarizationSetBy = Automatic

	column 'Numero Rua'
		dataType: string
		lineageTag: 054303cc-d09d-4e44-8a85-c56f442b6642
		summarizeBy: none
		sourceColumn: Numero Rua

		annotation SummarizationSetBy = Automatic

	column Complemento
		dataType: string
		lineageTag: 4b338739-e01f-4085-bc9c-1cc55e2ed827
		summarizeBy: none
		sourceColumn: Complemento

		annotation SummarizationSetBy = Automatic

	column Bairro
		dataType: string
		lineageTag: 486fb039-d25b-4e87-8882-74bc6be9a52d
		summarizeBy: none
		sourceColumn: Bairro

		annotation SummarizationSetBy = Automatic

	column Cep
		dataType: string
		lineageTag: ca79438a-6841-4aca-ba60-78666279ead4
		summarizeBy: none
		sourceColumn: Cep

		annotation SummarizationSetBy = Automatic

	column Produto
		dataType: string
		lineageTag: 048d1a5b-ab1b-4762-af18-9496fbf21d2b
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column 'Data da Coleta'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c272ee3f-cec8-44e0-be12-4994e3f318c8
		summarizeBy: none
		sourceColumn: Data da Coleta

		variation Variation
			isDefault
			relationship: 36c70ba1-1d9c-49b2-8faf-75f872eb888d
			defaultHierarchy: LocalDateTable_96edbe03-2166-4cb7-85f8-426c3ba5cc8e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Valor de Venda'
		dataType: double
		lineageTag: a9de88cd-5466-4fe1-865a-ce1877630f35
		summarizeBy: sum
		sourceColumn: Valor de Venda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Valor de Compra'
		dataType: double
		lineageTag: ec92320f-0c5f-46ab-b111-986ae59a14fb
		summarizeBy: sum
		sourceColumn: Valor de Compra

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unidade de Medida'
		dataType: string
		lineageTag: a24a8b97-1fb4-4162-bf65-cefaac963f59
		summarizeBy: none
		sourceColumn: Unidade de Medida

		annotation SummarizationSetBy = Automatic

	column Bandeira
		dataType: string
		lineageTag: 283f502f-b63b-47b6-a767-fb928f609a6b
		summarizeBy: none
		sourceColumn: Bandeira

		annotation SummarizationSetBy = Automatic

	partition ca-2004-01 = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\franc\OneDrive - Xscient\Dados\Dados Brasil\DadosCombustiveis\2004\ca-2004-01.csv"),[Delimiter=";", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Regiao - Sigla", type text}, {"Estado - Sigla", type text}, {"Municipio", type text}, {"Revenda", type text}, {"CNPJ da Revenda", type text}, {"Nome da Rua", type text}, {"Numero Rua", type text}, {"Complemento", type text}, {"Bairro", type text}, {"Cep", type text}, {"Produto", type text}, {"Data da Coleta", type date}, {"Valor de Venda", type number}, {"Valor de Compra", type number}, {"Unidade de Medida", type text}, {"Bandeira", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

