table dfEldenRing
	lineageTag: 1891dd49-f300-4d8c-839b-353f91e0c0f5

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 2cd3162b-1805-4f2a-bd0c-3afe3345a453
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 654ed7bb-de51-469e-bcd9-9c549d049f96
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Media_Anual_Players
		dataType: int64
		formatString: 0
		lineageTag: eb271e82-bff7-4c07-8144-819984fb83ba
		summarizeBy: sum
		sourceColumn: Media_Anual_Players

		annotation SummarizationSetBy = Automatic

	partition dfEldenRing = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\franc\OneDrive - Xscient\Dados\GamesFromSoftware\Players\dfEldenRing.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Ano", Int64.Type}, {"Categoria", type text}, {"Media_Anual_Players", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

