table FromSoftwareBuscas
	lineageTag: 54c89a7f-84e9-4ab7-9c78-e26c87755709

	column Mês
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8e59802c-578a-4e5c-9eb1-80419f4ffc45
		summarizeBy: none
		sourceColumn: Mês

		variation Variation
			isDefault
			relationship: 9f753a8b-0ba6-46a7-9289-688d197963b6
			defaultHierarchy: LocalDateTable_266db124-5e53-4394-8175-16e1425a2c70.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'FromSoftware: (Brasil)'
		dataType: int64
		formatString: 0
		lineageTag: b90ae2f6-d673-4773-a0c7-41068af5016f
		summarizeBy: sum
		sourceColumn: FromSoftware: (Brasil)

		annotation SummarizationSetBy = Automatic

	partition FromSoftwareBuscas = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\franc\OneDrive - Xscient\Dados\GamesFromSoftware\Buscas\FromSoftwareBuscas.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Column1", type text}, {"Column2", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Categoria: Todas as categorias", type text}, {"", type text}}),
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Tipo Alterado1", [PromoteAllScalars=true]),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos1",{{"", type text}, {"_1", type text}}),
				    #"Cabeçalhos Promovidos2" = Table.PromoteHeaders(#"Tipo Alterado2", [PromoteAllScalars=true]),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos2",{{"Mês", type date}, {"FromSoftware: (Brasil)", Int64.Type}})
				in
				    #"Tipo Alterado3"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

